### ISSUE TITLE
Trackerboy playback speed differs from gbt-player in emulators

### ISSUE THREAD

**Issue by tadashibashi** [stoneface86/trackerboy#15]
## Bug description

Trackerboy playback is slightly slower than playback in emulators (tested in SameBoy, Emulicious, GB Studio).
I'm using GB Studio's GBT Player with the same tick speed as in Trackerboy. Either increasing or decreasing tick speed doesn't align.

## How to reproduce

1. Write equivalent song with tempo ticks in .mod (F04) file as a .tbm (F40)
2. Play back .mod in GB Studio or build ROM to test in other emulators

## Information

 - Trackerboy version: v0.6.2

[SourceFiles.zip](https://github.com/stoneface86/trackerboy/files/9996473/SourceFiles.zip)
[GBSpeedComparisonFiles.zip](https://github.com/stoneface86/trackerboy/files/9996465/GBSpeedComparisonFiles.zip)

**Comment by stoneface86** [comment]
Interesting, I'm guessing the naive assumption of a vblank being exactly 59.7 Hz is the cause as each tick gets samplerate / 59.7 samples (with an extra sample on some ticks after accumulating the remainder).

I'll have to test this in the Nim rewrite to see if the same problem occurs there, which would confirm this an architectural problem with the emulator.
