### ISSUE TITLE
macOS Mojave 10.14 support

### ISSUE THREAD

**Issue by sttng** [stoneface86/trackerboy#18]
I am using an older macOS Version (10.14). Would it be possible to release a version compatible with this old OS ?

**Comment by stoneface86** [comment]
Sure, I can try for compatibility with Mojave. Qt 6.4 does support it, I'll just have to get a Mojave VM running as I currently do all my MacOS building on Monterey.

**Comment by sttng** [comment]
That'll be nice. I know Mojave is already deprecated, but I have some old 32bit macOS software running, so I'm staying with Mojave as long as possible and as long as my (old) MBP doesn't break.

**Comment by stoneface86** [comment]
I was able to get a build working, but I had to use Qt 6.2.0 instead of ~~6.4.4~~ 6.4.2.

I attached a zip of the build I tested. Let me know if this works for you.

[trackerboy_v0_6_3_osx_x64_mojave.zip](https://github.com/stoneface86/trackerboy/files/10584965/trackerboy_v0_6_3_osx_x64_mojave.zip)

**Comment by sttng** [comment]
Thats very kind of you. I gave it a try and it works flawless for all functions I tested (except for a missing App Icon). Thank you so much. Might add this file to releases. Waiting for a way to use TrackerBoy files on real hardware !

**Comment by stoneface86** [comment]
Fixed the missing icon, CMake didn't set the `CFBundleIconFile` key in the bundle's Info.plist. Yet my Monterey vm had no problem finding the icon without it.

[trackerboy_v0_6_3_osx_x64_mojave.zip (fixed)](https://github.com/stoneface86/trackerboy/files/10593838/trackerboy_v0_6_3_osx_x64_mojave.zip)

**Comment by sttng** [comment]
Yeah I have a nice TB Pixel Keyboard icon now :)
